apiVersion: v1
kind: Service
metadata:
  namespace: microservices
  name: order-app-service
  labels:
    app: order
    component: app
    env: {{ .Values.labels.env }}
spec:
  type: ClusterIP
  selector:
    app: order
    component: app
  ports:
    - name: http-order
      appProtocol: http
      port: 80
      targetPort: 8080
