apiVersion: apps/v1
kind:  StatefulSet
metadata:
  namespace: microservices
  name: customer-db-pod
  labels:
    app: customer
    component: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
      component: db
  serviceName: customer-db-service
  template:
    metadata:
      labels:
        app: customer
        component: db
    spec:
      containers:
        # MySQLコンテナ（開発環境のみ）
        - name: mysql
          image: mysql:5.7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: dev_db
            - name: MYSQL_USER
              value: dev_user
            - name: MYSQL_PASSWORD
              value: dev_password
          volumeMounts:
            - name: customer-db-host-path-persistent-volume-claim
              # NOTE:
              # mysqld: Can't create/write to file '/var/lib/mysql/is_writable' (Errcode: 13 - Permission denied)
              # datadirにマウントできない．
              mountPath: /var/volume
  volumeClaimTemplates:
    - metadata:
        name: customer-db-host-path-persistent-volume-claim
        labels:
          app: customer
          component: db
      spec:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        selector:
          matchLabels:
            component: db
            type: hostPath
